### ISSUE TITLE
1.13.0 beta RichText control error prevents webpart from loading

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-fx-controls-react#263]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.13.0-beta]

#### Expected / Desired Behavior / Question
The [RichText](https://github.com/SharePoint/sp-dev-fx-controls-react/blob/dev/docs/documentation/docs/controls/RichText.md) control works is rendered when the documentation steps are followed.

#### Observed Behavior
As soon as include the RichText component in a .tsx file, the webpart fails to load.
```jsx
<RichText value="<div>1stline</div><div>2ndline</div>"
          onChange={(val) => {console.log(val); return val;}} />
```
UI error
```
[SPLoaderError.loadComponentError]:
***Failed to load component "85f21334-e106-4c04-b690-0df567085926" (PersonBioPageLayoutWebPart).
Original error: ***The entry point for component "85f21334-e106-4c04-b690-0df567085926" (PersonBioPageLayoutWebPart) has a dependency on "ControlStrings" that is not declared in the manifest.

***INNERERROR:
***The entry point for component "85f21334-e106-4c04-b690-0df567085926" (PersonBioPageLayoutWebPart) has a dependency on "ControlStrings" that is not declared in the manifest.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-15.008/sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889:16049)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-15.008/sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512:21125)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-15.008/sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512:16214)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-15.008/sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512:12245)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-15.008/sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512:60385
```
Console errors
```
VM223:5 GET https://relative-path.invalid/ControlStrings net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ VM223:5
(anonymous) @ VM223:4
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:4
Promise.then (async)
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
i @ VM223:4
(anonymous) @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
(anonymous) @ VM223:4
Promise.then (async)
d @ VM223:4
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
s @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
import @ VM223:4
(anonymous) @ VM223:4
e.systemImport @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
c @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
i @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
o @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
n @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.loadComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.onLoad @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:91
t._load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._runApplicationManager @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._executePlatformCode @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.start @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
startSpfx @ Bio1.aspx?Mode=Edit:63
(anonymous) @ Bio1.aspx?Mode=Edit:71
(anonymous) @ Bio1.aspx?Mode=Edit:88
VM223:5 GET https://relative-path.invalid/@microsoft/sp-lodash-subset net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ VM223:5
(anonymous) @ VM223:4
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:4
Promise.then (async)
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
i @ VM223:4
(anonymous) @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
(anonymous) @ VM223:4
Promise.then (async)
d @ VM223:4
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
s @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
import @ VM223:4
(anonymous) @ VM223:4
e.systemImport @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
c @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
i @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
o @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
n @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.loadComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.onLoad @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:91
t._load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._runApplicationManager @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._executePlatformCode @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.start @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
startSpfx @ Bio1.aspx?Mode=Edit:63
(anonymous) @ Bio1.aspx?Mode=Edit:71
(anonymous) @ Bio1.aspx?Mode=Edit:88
VM223:5 GET https://relative-path.invalid/ControlStrings net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ VM223:5
(anonymous) @ VM223:4
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:5
(anonymous) @ VM223:4
Promise.then (async)
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
i @ VM223:4
(anonymous) @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
(anonymous) @ VM223:4
Promise.then (async)
d @ VM223:4
u @ VM223:4
l @ VM223:4
(anonymous) @ VM223:4
s @ VM223:4
(anonymous) @ VM223:4
Promise.then (async)
import @ VM223:4
(anonymous) @ VM223:4
e.systemImport @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
c @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
i @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
o @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.catch (async)
o @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
n @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.loadComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.onLoad @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:91
t._load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._runApplicationManager @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._executePlatformCode @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.start @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
startSpfx @ Bio1.aspx?Mode=Edit:63
(anonymous) @ Bio1.aspx?Mode=Edit:71
(anonymous) @ Bio1.aspx?Mode=Edit:88
sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889 Uncaught (in promise) Error
    at t [as constructor] (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889)
    at new t (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at Function.e.buildErrorWithVerboseLog (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at Function.e.buildLoadComponentError (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889
t @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.buildErrorWithVerboseLog @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.buildLoadComponentError @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.storeComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
n @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.loadComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.onLoad @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:91
t._load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._runApplicationManager @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._executePlatformCode @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.start @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
startSpfx @ Bio1.aspx?Mode=Edit:63
(anonymous) @ Bio1.aspx?Mode=Edit:71
(anonymous) @ Bio1.aspx?Mode=Edit:88
sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889 Uncaught (in promise) Error
    at t [as constructor] (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889)
    at new t (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at Function.e.buildErrorWithVerboseLog (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at Function.e.buildLoadComponentError (sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512)
    at sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:889
t @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.buildErrorWithVerboseLog @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.buildLoadComponentError @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.catch (async)
t.loadComponent @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.loadComponentById @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
t.onLoad @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:91
t._load @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:2324
e._runApplicationManager @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._executePlatformCode @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e.startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
e._startApplication @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
(anonymous) @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
Promise.then (async)
e.start @ sp-pages-assembly_en-us_2676c0dcef2e33d08d5b8433ef878499.js:1512
startSpfx @ Bio1.aspx?Mode=Edit:63
(anonymous) @ Bio1.aspx?Mode=Edit:71
(anonymous) @ Bio1.aspx?Mode=Edit:88
VM223:5 GET https://relative-path.invalid/@microsoft/sp-lodash-subset net::ERR_CONNECTION_TIMED_OUT
```

#### Steps to Reproduce
Scaffold an SPFx v1.8 project using pnpm's --shamefully-flatten flag, Node v8.15.1 and npm v6.4.1.
Install the beta version of pnp controls
```cmd
pnpm install @pnp/spfx-controls-react@next --save --shamefully-flatten
```
Include RichText control with or without a value as per the documentation.
```
gulp bundle
gulp package-solution
gulp serve
```
Deploy sppkg file and add webpart to a site page.

**Comment by hugoabernier** [comment]
Hi @semopz , sorry that you're experiencing difficulties.

I believe that the error message is because the control is looking for localized strings which haven't been declared yet.

Try the following.

Once the package is installed, you will have to configure the resource file of the property controls to be used in your project. You can do this by opening the `config/config.json` and adding the following line to the localizedResources property:

```JSON
"ControlStrings": "node_modules/@pnp/spfx-controls-react/lib/loc/{locale}.js"
```

I hope this helps?

**Comment by semopz** [comment]
It looks like ControlStrings is in place and the locale I require is available in the listed location. 

I think this might have something to do with me using rush stack 3.2. I'm doing some more testing.

Also wanted to ask if this control can be configured to support inline images? Let me know if I need to post another topic.

Thanks

**Comment by hugoabernier** [comment]
@semopz it may be a good idea to see if the issue is specific to `RichText` or with the PnP package in general. Do you get the same problem if you include a different control that uses a localized resource (like the `WebPartTitle` control with the default properties)?

RE: Inline images. Our first priority was to give an experience as close as possible to the existing Rich Text Editor. Since it didn't support inline images, we chose not to support them -- but that doesn't mean that it shouldn't be included.

There are still a few things I'd like to add, like table support, block style support (for multiline blockquotes), and inline images, but feedback like yours will help us prioritize. 

It wouldn't hurt to create a separate issue to request inline image support.

Thanks for using the RichText control. Let me know how it goes.

**Comment by semopz** [comment]
Thanks, I'll raise a request now and I'll continue testing to see if I can get to the bottom of this issue.

Could you confirm if it is supposed to work with IE11? I'm doing most of my testing in Chrome but I'll need to make sure that it works in IE11 as well.

**Comment by semopz** [comment]
The issue seems to have gone away. I uninstalled and removed the app then deployed a production version. After this, the webpart started working again.
